name: build tailscale

on:
  workflow_dispatch:

jobs:
  build-tailscale:
    permissions: write-all
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Checkout TailscaleForMagisk
        uses: actions/checkout@v4
        with:
          path: TailscaleForMagisk
      - name: Checkout tailscale
        uses: actions/checkout@v4
        with:
          repository: tailscale/tailscale
          ref: v${{ vars.TAILSCALE_BRANCH }}
          path: tailscale
      - name: apply patch & build
        run: |
          cd tailscale
          patch -p1 < ../TailscaleForMagisk/feature_support_android_lastest.patch
          git config --global user.email "build@github.com"
          git config --global user.name "build"
          git add -A && git commit -m "commit"
          make buildlinuxarm
          cp /home/runner/go/bin/linux_arm/tailscale ../TailscaleForMagisk/src
          cp /home/runner/go/bin/linux_arm/tailscaled ../TailscaleForMagisk/src
          cd ..
      - name: Update version and versionCode
        run: |
          current_date=$(date +'%Y%m%d')
          sed -i "s/^version=.*/version=v${{ vars.TAILSCALE_BRANCH }}/" TailscaleForMagisk/src/module.prop
          sed -i "s/^versionCode=.*/versionCode=$current_date/" TailscaleForMagisk/src/module.prop
      - name: Archive project
        run: cd TailscaleForMagisk/src && zip -r ../../TailscaleForMagisk.zip *
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: project-archive
          path: TailscaleForMagisk.zip
      - name: Create Tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ vars.TAILSCALE_BRANCH }}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ vars.TAILSCALE_BRANCH }}
          files: TailscaleForMagisk.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
